language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  matrix:
    - CONF=debug   ARCH=x86_64
    - CONF=release ARCH=x86_64
    - CONF=debug   ARCH=x86
    - CONF=release ARCH=x86

before_install:
  - echo $LANG
  - echo $TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" == "linux" -a "$ARCH" == "x86" ]; then
        sudo apt-get update;
        sudo apt-get install -qq g++-multilib libc6-dbg:i386;
    fi

install: true

before_script:
  - mkdir build
  - echo ${ARCH}
  - if [ "${ARCH}" == "x86" ]; then ARCH_FLAGS=-m32; else ARCH_FLAGS=-m64; fi
  - (cd build &&
     cmake -DCMAKE_VERBOSE_MAKEFILE=ON
     -DCMAKE_BUILD_TYPE=$CONF
     -DCMAKE_CXX_FLAGS="$ARCH_FLAGS"
     ..)

script:
  - cd build
  - make

after_success:
  - ./Tutorial 5

after_failure:
  - echo build failure

