language: cpp

os:
  - linux
  - osx

complier:
  - gcc
  - clang

env:
  matrix:
    - CONF=debug   ARCH=x86_64
    - CONF=release ARCH=x86_64
    - CONF=debug   ARCH=x86
    - CONF=release ARCH=x86
    allow_failures:
      - os: osx

before_install:
  - echo $LANG
  - echo $TRAVIS_OS_NAME
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -qq cmake llvm-3.4 clang-3.4 libc++1; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install cmake; fi
  - clang -v
  - uname -a

install: true

before_script:
  - mkdir build
  - cd build && cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=$CONF ..

script:
  - cd build
  - make

after_success:
  - echo build success

after_failure:
  - echo build failure

