language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  matrix:
    - CONF=debug   ARCH=x86_64
    - CONF=release ARCH=x86_64
    - CONF=debug   ARCH=x86
    - CONF=release ARCH=x86

before_install:
  - echo $LANG
  - echo $TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" == "linux" && "$ARCH" = "x86" ]; then sudo apt-get install -qq g++-multilib libc6-dbg:i386; fi

install: true

before_script:
  - mkdir build
  - eval "ARCH=${ARCH}";
     (cd build && cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=$CONF ..)

script:
  - cd build
  - make

after_success:
  - echo build success

after_failure:
  - echo build failure

