version: 1.0.{build}

configuration:
- Debug
- Release

environment:
  matrix:
  - VS_VERSION: 12
    VS_PLATFORM: win32
  - VS_VERSION: 12
    VS_PLATFORM: x64
  - VS_VERSION: 14
    VS_PLATFORM: win32
  - VS_VERSION: 14
    VS_PLATFORM: x64

before_build:
- cmake -H. -BBuild -G "Visual Studio %VS_VERSION%" -DCMAKE_GENERATOR_PLATFORM=%VS_PLATFORM% -DBUILD_SHARED_LIBS=true

build:
  project: Build\Tutorial.sln

